services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.41
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: turbo_db
      MYSQL_USER: turbo
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
    driver: local
